package com.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
 *  Author:     Ovezmyrat Arnazarov
 *  Semester:   Spring-2022
 *  Class Description:  This class creates a Patient entity as an item for the DynamoDB table called "patients".
 *                      All properties of an entity created as an attribute for the "patients" table.
 *                      The last property "vitals" is another entity class with three properties.
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "patients")
public class Patient {

    @DynamoDBHashKey(attributeName="patientID")
    @DynamoDBAutoGeneratedKey
    private String patientID;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String birthdate;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String phone;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute(attributeName="vitals")
    private Vitals vitals;
}
